# Generated by Django 5.0.2 on 2024-03-03 05:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('sur_name', models.CharField(max_length=55)),
                ('age', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('salary', models.PositiveIntegerField()),
                ('status', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hire_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('sur_name', models.CharField(max_length=55)),
                ('age', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('password_ser', models.CharField(max_length=155)),
                ('password_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='History_contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('property', models.CharField(max_length=255, verbose_name='enter the property ID')),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_duration', models.IntegerField()),
                ('agents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agents')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rent', models.BooleanField(default=False)),
                ('volume', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('luxurious', 'Luxurious'), ('excellent', 'Excellent'), ('good', 'Good')], default='good', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('courtyard', 'Courtyard')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='estate_photo/', validators=[django.core.validators.RegexValidator(code='invalid_image_format', message='Invalid image format. Supported formats: JPG, JPEG, PNG, GIF, BMP, SVG', regex='image_regex_pattern')])),
                ('rooms', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='building_images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.CharField(max_length=100)),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('rent', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.CharField(max_length=255, verbose_name='enter the property ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Meeting time')),
                ('agents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.agents')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proproperty', models.CharField(max_length=255, verbose_name='enter the property ID')),
                ('payment_date', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customers')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept', models.ImageField(upload_to='estate_photo/', validators=[django.core.validators.RegexValidator(code='invalid_image_format', message='Invalid image format. Supported formats: JPG, JPEG, PNG, GIF, BMP, SVG', regex='image_regex_pattern')])),
                ('data_issued', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.payment')),
            ],
        ),
    ]
